
import { Language } from './types';

export const FOOD_ITEMS = [
  "Broccoli", "Spinach", "Kale", "Blueberries", "Strawberries", "Salmon", "Tuna", 
  "Walnuts", "Almonds", "Flaxseeds", "Turmeric", "Garlic", "Green Tea", "Tomatoes", 
  "Carrots", "Sweet Potatoes", "Greek Yogurt", "Lentils", "Chickpeas", "Quinoa", 
  "Oats", "Brown Rice", "Avocado", "Olive Oil", "Chicken Breast", "Turkey", "Eggs", 
  "Tofu", "Edamame", "Mushrooms", "Bell Peppers", "Oranges", "Apples", "Grapes", 
  "Pomegranate", "Dark Chocolate (70%+)", "Ginger", "Lemon", "Chia Seeds", "Pumpkin Seeds", 
  "Cauliflower", "Brussels Sprouts", "Cabbage", "Asparagus", "Beets", "Watermelon", 
  "Papaya", "Kiwi", "Cherries", "Raspberries"
];

export const HEALTH_CONDITIONS = [
  "Diabetes (Type 1)", "Diabetes (Type 2)", "Hypertension", "Kidney Disease", 
  "Liver Disease", "Heart Condition", "High Cholesterol", "None / Healthy"
];

// Configuration for specific lab inputs
export const LAB_INPUTS = {
  'blood-analysis': [
    { key: 'hemoglobin', label: 'Hemoglobin (Hb)', unit: 'g/dL', placeholder: '12.0 - 15.5' },
    { key: 'wbc', label: 'White Blood Cells (WBC)', unit: 'cells/mcL', placeholder: '4500 - 11000' },
    { key: 'rbc', label: 'Red Blood Cells (RBC)', unit: 'million/mcL', placeholder: '4.0 - 5.5' },
    { key: 'platelets', label: 'Platelets', unit: 'cells/mcL', placeholder: '150000 - 450000' }
  ],
  'kidney-analysis': [
    { key: 'creatinine', label: 'Serum Creatinine', unit: 'mg/dL', placeholder: '0.6 - 1.2' },
    { key: 'egfr', label: 'eGFR', unit: 'mL/min', placeholder: '> 90' },
    { key: 'bun', label: 'Blood Urea Nitrogen (BUN)', unit: 'mg/dL', placeholder: '7 - 20' },
    { key: 'urea', label: 'Urea', unit: 'mg/dL', placeholder: '15 - 45' }
  ],
  'liver-analysis': [
    { key: 'alt', label: 'ALT (SGPT)', unit: 'U/L', placeholder: '7 - 56' },
    { key: 'ast', label: 'AST (SGOT)', unit: 'U/L', placeholder: '10 - 40' },
    { key: 'bilirubin', label: 'Total Bilirubin', unit: 'mg/dL', placeholder: '0.1 - 1.2' },
    { key: 'albumin', label: 'Albumin', unit: 'g/dL', placeholder: '3.4 - 5.4' }
  ],
  'diabetes': [
    { key: 'fasting_glucose', label: 'Fasting Glucose', unit: 'mg/dL', placeholder: '70 - 99' },
    { key: 'post_prandial', label: '2h Post-Prandial', unit: 'mg/dL', placeholder: '< 140' },
    { key: 'hba1c', label: 'HbA1c (Cumulative)', unit: '%', placeholder: '< 5.7' },
    { key: 'insulin', label: 'Insulin', unit: 'mIU/L', placeholder: '2.6 - 24.9' }
  ]
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    app_name: "Cancer Care",
    welcome_title: "Journey to Recovery",
    welcome_subtitle: "Advanced AI Support for Breast Cancer Patients",
    signin: "Sign In",
    signup: "Create Account",
    email: "Email Address",
    password: "Password",
    name: "Full Name",
    phone: "Phone Number",
    phone_note: "Add phone to receive important updates",
    home: "Home",
    nutrition: "Nutrition",
    blood: "Blood Labs",
    kidney: "Kidney Function",
    liver: "Liver Function",
    diabetes: "Diabetes",
    reminders: "Reminders",
    chat: "AI Medical Assistant",
    profile: "Profile",
    history: "Medical History",
    settings: "Settings",
    language: "Language",
    dark_mode: "Dark Mode",
    analyze: "Analyze Report",
    upload_report: "Upload Report (Image)",
    generate_plan: "Generate Medical Nutrition Plan",
    height: "Height (cm)",
    weight: "Weight (kg)",
    age: "Age",
    stage: "Cancer Stage (e.g., Stage II)",
    diagnosis_date: "Date of Diagnosis",
    activity: "Activity Level",
    select_foods: "Preferred Foods",
    select_conditions: "Existing Health Conditions",
    results: "Analysis Results",
    enter_values: "Manual Data Entry",
    save: "Save Changes",
    update: "Update Stats",
    cancel: "Cancel",
    logout: "Log Out",
    copyright: "© 2025 Mazen Saydain. All rights reserved.",
    contact_dev: "Contact Developer",
    ai_disclaimer: "AI analysis is for informational purposes only. Consult a doctor.",
    type_message: "Ask a medical question...",
    loading: "Processing Data...",
    no_account: "No account?",
    have_account: "Have an account?",
    welcome_back: "Welcome,",
    latest_updates: "Latest Updates",
    health_status: "Health Status",
    pending: "Pending Analysis",
    good: "Stable",
    medication_due: "Upcoming Medication",
    enable_email: "Email Reminder",
    email_scheduled: "Reminder Scheduled",
    email_desc: "Email notification set.",
    history_empty: "No actions recorded yet.",
    weekly_update: "Weekly data refresh required. Please update your stats.",
    clear_history: "Clear History",
    analyze_btn: "Calculate & Analyze Results"
  },
  ar: {
    app_name: "Cancer Care",
    welcome_title: "رحلة التعافي",
    welcome_subtitle: "نظام رعاية ذكي لمرضى سرطان الثدي",
    signin: "تسجيل الدخول",
    signup: "إنشاء حساب جديد",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    name: "الاسم الكامل",
    phone: "رقم الهاتف",
    phone_note: "أضف رقمك لاستقبال التحديثات الهامة",
    home: "الرئيسية",
    nutrition: "التغذية العلاجية",
    blood: "تحليل الدم",
    kidney: "وظائف الكلى",
    liver: "وظائف الكبد",
    diabetes: "السكري",
    reminders: "التذكيرات",
    chat: "المساعد الطبي",
    profile: "الملف الشخصي",
    history: "السجل الطبي",
    settings: "الإعدادات",
    language: "اللغة",
    dark_mode: "الوضع الليلي",
    analyze: "تحليل التقرير",
    upload_report: "رفع صورة التقرير",
    generate_plan: "إنشاء خطة تغذية علاجية",
    height: "الطول (سم)",
    weight: "الوزن (كجم)",
    age: "العمر",
    stage: "مرحلة المرض (مثال: المرحلة الثانية)",
    diagnosis_date: "تاريخ التشخيص",
    activity: "مستوى النشاط",
    select_foods: "الأطعمة المفضلة",
    select_conditions: "الحالات الصحية المزمنة",
    results: "نتائج التحليل",
    enter_values: "إدخال يدوي للبيانات",
    save: "حفظ التغييرات",
    update: "تحديث البيانات",
    cancel: "إلغاء",
    logout: "تسجيل الخروج",
    copyright: "© 2025 مازن صيدين. جميع الحقوق محفوظة.",
    contact_dev: "تواصل مع المطور",
    ai_disclaimer: "تحليلات الذكاء الاصطناعي للأغراض المعلوماتية فقط. استشر الطبيب.",
    type_message: "اطرح سؤالاً طبياً...",
    loading: "جاري المعالجة...",
    no_account: "ليس لديك حساب؟",
    have_account: "لديك حساب؟",
    welcome_back: "مرحباً،",
    latest_updates: "آخر التحديثات",
    health_status: "الحالة الصحية",
    pending: "بانتظار التحليل",
    good: "مستقرة",
    medication_due: "الدواء القادم",
    enable_email: "تذكير عبر البريد",
    email_scheduled: "تمت الجدولة",
    email_desc: "تم ضبط الإشعار.",
    history_empty: "لا توجد سجلات سابقة.",
    weekly_update: "مطلوب تحديث البيانات الأسبوعي.",
    clear_history: "مسح السجل",
    analyze_btn: "حساب وتحليل النتائج"
  }
};
